### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by error414** [teckel12/LuaTelemetry#170] opened 2018-08-25 19:09 UTC
Hi,

I have problem wit last verision (cloned from github, used dist folder). After activate Inav lua script in "Display" page "Screen 1 Script iNav", taranis is slow as hell.

See video, I think that it is best description.  https://youtu.be/mPPkhgMAR0k

**Comment by teckel12** [comment] 2018-08-25 23:27
@error414 Has something to do with the release OpenTX 2.2.2  It wasn't doing this before.

**Comment by teckel12** [comment] 2018-08-26 01:54
@error414 See: https://github.com/opentx/opentx/issues/6127

**Comment by teckel12** [comment] 2018-08-26 02:41
@error414 Try Lua Telemetry v1.4.1 and report back.

**Comment by zingaros** [comment] 2018-08-26 07:52
Hello, 
User of the former version (1.3.1), I tried today the v1.4.1 on a Taranis X9D+ with OpenTX 2.2.2: pilot view is gorgeous (kudo!) but voice is most of the time impacted: its not any more Amber that is speaking but Dark Vador :-)
Just checked See: opentx/opentx#6127, no worries, i will watch OpenTX changes.

**Comment by error414** [comment] 2018-08-26 08:37
Ahh, sorry, I forgot write that I use opentx 2.2.2, it's nice you was able to find out from screen.
I have pulled last version and I can confirm, it WORKS fast. Tank you very much.

**Comment by zingaros** [comment] 2018-08-26 10:11
@error414 are you also experiencing, wile having the script activated, voice issues or I’m the only one (see my comment above)? Many thanks

**Comment by error414** [comment] 2018-08-26 12:33
https://youtu.be/7GikKAZwESk sound is still bad :(  

once happend to me that I got lua script error and then taranis said that he dosnt see SD card

**Comment by teckel12** [comment] 2018-08-26 13:55
It seems OpenTX 2.2.2 is **much** slower with SD card access. I didn't experience any of these problems when using a pre-release of 2.2.2 either. So somewhere in the 2.2.2 process something drastically changed.

The OpenTX team currently seems to be more interested in pointing blame than looking into the issue.  But I'm confident with enough evidence they'll look into it.

The solution for the short term may be to install a pre-release version of 2.2.2. I'm going to try a few versions I happened to download which may also help to isolate the problem with OpenTX.

**Comment by teckel12** [comment] 2018-08-27 03:12
@error414 Try using OpenTX firmware without the `luac` box checked. It seems that option drastically slows down OpenTX when there's SD card access. That change along with Lua Telemetry v1.4.1 should result in **MUCH** faster results. I get no "Darth Vader" voice alerts either with `luac` turned off.

Let me know how that works. Thanks.

**Comment by teckel12** [comment] 2018-08-27 03:16
@zingaros Try updating the OpenTX firmware to not include the `luac` option, that seems to be causing the fantastic slowdown and resulting voice problems. Also, I believe this issue is made much worse if you're using an extremely slow SD card as I don't experience it nearly as bad as you're experiencing. Just something to keep in mind.

**Comment by teckel12** [comment] 2018-08-27 19:58
@error414 Your SD card must have very slow access.  The slower the SD card access, the more pronounced any slowdown will be.  There's a few things I'm doing with Lua Telemetry to try and address this issue.  I feel confident I can get the Darth Vader voice straightened up in a day or two.

The OpenTX team has been very unsupportive in my attempts to isolate and resolve the issue.  With that said, they did finally acknowledged there's some room for improvement and a change may very well happen.  After sorting out what I can change with Lua Telemetry, I plan on looking into the OpenTX code to address the issue directly.  But, OpenTX releases happen VERY infrequently, so this isn't really a solution as that could easily be 6 months away even if the change was merged today.

In any case, I'll continue to work on Lua Telemetry to resolve the Darth Vader voice issue.  I'll post back here with any updates.

**Comment by error414** [comment] 2018-08-27 20:51
hmm, it is possible, I use old 8GB SD card, it should be class 10 but who knows. I wanted to try samsung evo 64GB but it seems that taranis doesn't suport 64GB sd card. 
![sdcard](https://user-images.githubusercontent.com/1698092/44685296-6cd57e00-aa4b-11e8-8797-7b3a693bf142.png)

**Comment by teckel12** [comment] 2018-08-28 05:08
@error414 Try this pre-release build of 1.4.2: [LuaTelemetry1.4.2.zip](https://github.com/iNavFlight/LuaTelemetry/files/2326574/LuaTelemetry1.4.2.zip)

Just copy the contents to the `\SCRIPTS\TELEMETRY\` folder on your transmitter's SD card.  Let me know if the "Darth Vader" voice is gone as a result.  I feel very confident that it will sound much better with this pre-release.

The OpenTX team has also been working on cleaning up some code having to do with this.  It should be included in the 2.2.3 release of OpenTX.

**Comment by zingaros** [comment] 2018-08-28 20:26
hello
i followed your exchanges on Open TX: whaoo! Great job!
i tested the pre-release build of 1.4.2 : not working for me. it says "script syntax error". I tried several time with and without telemetry feed. Tested on Open TX 2.2.2 with the option no heli (luac is not enabled) on a taranis 9xd+.
Hope this helps, let me know if any debug option need to be activated or whatsoever, not super familiar with Lua and OpenTx dev.

**Comment by error414** [comment] 2018-08-28 20:28
@teckel12 1.4.2 works!!! without darth vader voice

**Comment by teckel12** [comment] 2018-08-28 21:16
@zingaros A script syntax error typically means that you have a mix-up in versions of Lua Telemetry files.  For example, if you just copy the `iNav.lua` file, you're almost guaranteed to have problems.  For the [LuaTelemetry1.4.2.zip](https://github.com/iNavFlight/LuaTelemetry/files/2326574/LuaTelemetry1.4.2.zip) file, make sure you copy the `iNav.lua` file as well as the `iNav` folder to your SD card's `\SCRIPTS\TELEMETRY\` folder.

FYI, the firmware options won't matter as far as running Lua Telemetry.  I would suggest `noheli` and `lua`, but neither are needed for Lua Telemetry to function.  Previously, I would have also suggested the `luac` option as well, but with 2.2.1/2.2.2 it's causing unnecessary file access.  So that option is up for debate till they release 2.2.3 which should include a fix.

**Comment by teckel12** [comment] 2018-08-28 21:38
f

**Comment by teckel12** [comment] 2018-08-29 01:35
History...

1. Issue reported with Lua Telemetry
1. Problem isolated to OpenTX's `luac` option
1. Fixed Lua Telemetry to get around OpenTX `luac` bug
1. Posted issue with OpenTX reporting `luac` option bug
1. OpenTX contributors attack because their code is bug free
1. Finger pointing that it's not a bug in OpenTX, but lazy programming with Lua Telemetry
1. OpenTX contributors angry that I didn't say I was sorry for incorrectly identifying where the bug was **in their code**
1. Pull request to fix OpenTX even though it's bug free and there's no way it could be a bug in OpenTX
1. Lua Telemetry updated further to get around OpenTX `luac` bug till the fix is released
1. In denial and history revisionist OpenTX contributors continue to point blame even through there's a pull request that fixes the bug in OpenTX
1. Challenging OpenTX contributors that the above is what happened causes them to delete my message, as they can't argue with the truth

What a cheery group of individuals!  They seriously need to work on their customer support and triage skills.

**Comment by teckel12** [comment] 2018-08-29 20:14
@zingaros I'll create a new package and make sure everything is up to date.

**Comment by teckel12** [comment] 2018-08-29 22:39
@zingaros Try this: [LuaTelemetry-1.4.2b.zip](https://github.com/iNavFlight/LuaTelemetry/files/2334026/LuaTelemetry-1.4.2b.zip)

This assumes you already have 1.4.1 installed and these files go on top of your existing ones.  This was done with a new compile script in the hopes it would be more reliable.

**Comment by teckel12** [comment] 2018-08-30 12:48
@zingaros If it still crashes, try this version which includes debug info which may give some insight into the problem: [LuaTelemetry-1.4.2-debug.zip](https://github.com/iNavFlight/LuaTelemetry/files/2336186/LuaTelemetry-1.4.2-debug.zip)

This uses about 10k more memory, so it shouldn't be used long-term.  But, nice to be able to debug an isolated problem in a case like this.

**Comment by zingaros** [comment] 2018-08-30 13:02
Thanks
I will try tonight

**Comment by zingaros** [comment] 2018-08-30 20:43
@teckel12 Hello, 1.4.2b works perfectly 👍  so looks only it was a pb of packaging right?
Debug do script error but who cares? ;-) Thanks a lot for your continuous support!

**Closed as completed** 2018-09-28 12:46 UTC
Labels: bug, merged to development
